// Generated by GAS Prototype | Created by @agunk

function doGet(e) {
  // 1. ROUTING DOWNLOAD APK / EXPORT CSV
  if (e && e.parameter && e.parameter.export_id) {
    var content = CacheService.getScriptCache().get('export_' + e.parameter.export_id);
    if (content) {
      return ContentService.createTextOutput(content)
        .setMimeType(ContentService.MimeType.CSV)
        .downloadAsFile('Rekap_Iuran.csv');
    } else {
      return ContentService.createTextOutput('File kadaluarsa atau tidak ditemukan.');
    }
  }

  // 2. ROUTING REST API (Untuk React Vite PWA Frontend)
  if (e && e.parameter && e.parameter.action) {
    var action = e.parameter.action;
    try {
      if (action === 'getDashboardStats') return jsonResponse(getDashboardStats());
      if (action === 'getUsers') return jsonResponse(getUsers());
      if (action === 'getKaryawan') return jsonResponse(getKaryawan());
      if (action === 'getIuran') return jsonResponse(getIuran());
      if (action === 'getPengeluaran') return jsonResponse(getPengeluaran());
      if (action === 'getUndian') return jsonResponse(getUndian());
      if (action === 'getWaTemplate') return jsonResponse({ success: true, data: getWaTemplate() });
      if (action === 'verifySession') return jsonResponse(verifySessionToken(e.parameter.username, e.parameter.token));
      return jsonResponse({ success: false, message: 'Action tidak dikenali: ' + action });
    } catch (err) {
      return jsonResponse({ success: false, message: err.toString() });
    }
  }

  // 3. DEFAULT ROUTING: Render HTML Template (Untuk Blogspot / Iframe Pengguna Lama)
  const tmp = HtmlService.createTemplateFromFile('Index');
  
  // Suntik data dashboard langsung ke HTML agar tampil instan (0 detik)
  const stats = getDashboardStats();
  tmp.initialStats = JSON.stringify(stats.success ? stats.data : {});
  
  return tmp.evaluate()
    .setTitle('E-Anjangsana V.10.0')
    .addMetaTag('viewport', 'width=device-width, initial-scale=1')
    .setXFrameOptionsMode(HtmlService.XFrameOptionsMode.ALLOWALL);
}

// --- REST API POST HANDLER (Untuk React Vite PWA) ---
function doPost(e) {
  try {
    var data = {};
    if (e && e.postData && e.postData.contents) {
      try {
        data = JSON.parse(e.postData.contents);
      } catch (jsonErr) {
        data = e.parameter || {};
      }
    } else if (e && e.parameter) {
      data = e.parameter;
    }

    var action = data.action || (e && e.parameter ? e.parameter.action : '');
    
    if (action === 'login') {
      return jsonResponse(loginUser(data.username, data.password));
    }
    if (action === 'logout') {
      return jsonResponse(logoutUser(data.username));
    }
    if (action === 'saveKaryawan') {
      return jsonResponse(saveKaryawan(data));
    }
    if (action === 'saveIuran') {
      return jsonResponse(saveIuran(data));
    }
    if (action === 'savePengeluaran') {
      return jsonResponse(savePengeluaran(data));
    }
    if (action === 'saveUndian') {
      return jsonResponse(saveUndian(data));
    }
    if (action === 'saveUser') {
      return jsonResponse(saveUser(data));
    }
    if (action === 'saveSettingInfo') {
      return jsonResponse(saveSettingInfo(data.infoText));
    }
    if (action === 'saveSettingWA') {
      return jsonResponse(saveSettingWA(data.templateText));
    }
    if (action === 'resetStatusKaryawan') {
      return jsonResponse(resetStatusKaryawan());
    }
    if (action === 'deleteKaryawan') {
      return jsonResponse(deleteKaryawan(data.id));
    }
    if (action === 'deleteIuran') {
      return jsonResponse(deleteIuran(data.id));
    }
    if (action === 'deletePengeluaran') {
      return jsonResponse(deletePengeluaran(data.id));
    }
    if (action === 'deleteUndian') {
      return jsonResponse(deleteUndian(data.id));
    }
    if (action === 'deleteUser') {
      return jsonResponse(deleteUser(data.username));
    }

    return jsonResponse({ success: false, message: 'Action POST tidak valid: ' + action });
  } catch (err) {
    return jsonResponse({ success: false, message: err.toString() });
  }
}

function jsonResponse(data) {
  return ContentService.createTextOutput(JSON.stringify(data))
    .setMimeType(ContentService.MimeType.JSON);
}

// --- SECURITY: PASSWORD HASHING ---
function hashPassword(password) {
  const rawHash = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, password);
  let txtHash = '';
  for (let i = 0; i < rawHash.length; i++) {
    let hashVal = rawHash[i];
    if (hashVal < 0) { hashVal += 256; }
    if (hashVal.toString(16).length == 1) { txtHash += '0'; }
    txtHash += hashVal.toString(16);
  }
  return txtHash;
}

// --- AUTOMATED DATABASE SETUP ---
function setupDatabase() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  
  // 1. Users (UPDATED: Tambah kolom token dan Hash Default Passwords)
  let sheetUsers = ss.getSheetByName('Users');
  if (!sheetUsers) {
    sheetUsers = ss.insertSheet('Users');
    sheetUsers.appendRow(['username', 'password', 'fullname', 'role', 'photo', 'token']);
    sheetUsers.appendRow(['admin', hashPassword('Demo2026!'), 'Super Admin', 'Superadmin', '', '']);
    sheetUsers.appendRow(['bendahara', hashPassword('Demo2026!'), 'Bendahara Keuangan', 'Bendahara', '', '']);
    sheetUsers.setFrozenRows(1);
  } else {
    checkHeaders(sheetUsers, ['username', 'password', 'fullname', 'role', 'photo', 'token']);
  }
  
  // 2. Karyawan
  let sheetKaryawan = ss.getSheetByName('Karyawan');
  if (!sheetKaryawan) {
    sheetKaryawan = ss.insertSheet('Karyawan');
    sheetKaryawan.appendRow(['id', 'nama', 'jabatan', 'nominal_iuran', 'status']);
    sheetKaryawan.setFrozenRows(1);
  } else {
    checkHeaders(sheetKaryawan, ['id', 'nama', 'jabatan', 'nominal_iuran', 'status']);
  }
  
  // 3. Iuran
  let sheetIuran = ss.getSheetByName('Iuran');
  if (!sheetIuran) {
    sheetIuran = ss.insertSheet('Iuran');
    sheetIuran.appendRow(['id', 'tanggal', 'id_karyawan', 'nama_karyawan', 'periode', 'nominal', 'metode_pembayaran', 'uang_diterima', 'kembalian']);
    sheetIuran.setFrozenRows(1);
  } else {
    checkHeaders(sheetIuran, ['id', 'tanggal', 'id_karyawan', 'nama_karyawan', 'periode', 'nominal', 'metode_pembayaran', 'uang_diterima', 'kembalian']);
  }

  // 4. Pengeluaran
  let sheetPengeluaran = ss.getSheetByName('Pengeluaran');
  if (!sheetPengeluaran) {
    sheetPengeluaran = ss.insertSheet('Pengeluaran');
    sheetPengeluaran.appendRow(['id', 'tanggal', 'keterangan', 'nominal', 'kategori']);
    sheetPengeluaran.setFrozenRows(1);
  } else {
    checkHeaders(sheetPengeluaran, ['id', 'tanggal', 'keterangan', 'nominal', 'kategori']);
  }

  // 5. Undian
  let sheetUndian = ss.getSheetByName('Undian');
  if (!sheetUndian) {
    sheetUndian = ss.insertSheet('Undian');
    sheetUndian.appendRow(['id', 'tanggal', 'id_karyawan', 'nama_pemenang', 'periode']);
    sheetUndian.setFrozenRows(1);
  } else {
    checkHeaders(sheetUndian, ['id', 'tanggal', 'id_karyawan', 'nama_pemenang', 'periode']);
  }

  // 6. Settings
  let sheetSettings = ss.getSheetByName('Settings');
  if (!sheetSettings) {
    sheetSettings = ss.insertSheet('Settings');
    sheetSettings.appendRow(['key', 'value']);
    sheetSettings.appendRow(['info_dashboard', 'Selamat datang di sistem E-Anjangsana. Silakan cek tunggakan iuran Anda.']);
    sheetSettings.setFrozenRows(1);
  } else {
    checkHeaders(sheetSettings, ['key', 'value']);
  }
}

function checkHeaders(sheet, requiredHeaders) {
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
  requiredHeaders.forEach(function(h) {
    if (headers.indexOf(h) === -1) {
      sheet.getRange(1, headers.length + 1).setValue(h);
      headers.push(h);
    }
  });
}

// --- HELPER FUNCTIONS ---
function safeDateFormat(value) {
  if (!value) return '';
  if (value instanceof Date) {
    return Utilities.formatDate(value, Session.getScriptTimeZone(), 'yyyy-MM-dd');
  }
  return String(value);
}

function getColumnMap(sheet) {
  if (sheet.getLastColumn() === 0) return {};
  const headers = sheet.getRange(1, 1, 1, sheet.getLastColumn()).getValues()[0];
  const map = {};
  headers.forEach(function(h, i) { map[String(h).toLowerCase().trim()] = i; });
  return map;
}

function parseData(sheetName, formatter) {
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(sheetName);
  if (!sheet || sheet.getLastRow() <= 1) return [];
  const map = getColumnMap(sheet);
  const data = sheet.getDataRange().getValues();
  const result = [];
  for (var i = 1; i < data.length; i++) {
    result.push(formatter(data[i], map));
  }
  return result;
}

// --- AUTH & SECURITY LOGIC ---
function loginUser(username, password) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');
    if (!sheet) return { success: false, message: 'Database belum di-setup. Jalankan setupDatabase().' };
    
    const data = sheet.getDataRange().getValues();
    const map = getColumnMap(sheet);
    const hashedInput = hashPassword(password);
    
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][map['username']]) === String(username) &&
          String(data[i][map['password']]) === String(hashedInput)) {
        
        // Generate Token Baru Sesi Login
        const newToken = Utilities.getUuid();
        sheet.getRange(i + 1, map['token'] + 1).setValue(newToken);

        return {
          success: true,
          user: {
            username: data[i][map['username']],
            fullname: data[i][map['fullname']],
            role:     data[i][map['role']],
            photo:    data[i][map['photo']] || '',
            token:    newToken
          }
        };
      }
    }
    return { success: false, message: 'Username atau Password salah!' };
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function verifySessionToken(username, token) {
  if (!username || !token) return { valid: false };
  const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');
  if (!sheet) return { valid: false };
  const data = sheet.getDataRange().getValues();
  const map = getColumnMap(sheet);
  
  for (var i = 1; i < data.length; i++) {
    if (String(data[i][map['username']]) === String(username) &&
        String(data[i][map['token']]) === String(token)) {
      return { valid: true };
    }
  }
  return { valid: false };
}

function logoutUser(username) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(5000);
    const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Users');
    const data = sheet.getDataRange().getValues();
    const map = getColumnMap(sheet);
    for (var i = 1; i < data.length; i++) {
      if (String(data[i][map['username']]) === String(username)) {
        sheet.getRange(i + 1, map['token'] + 1).setValue(''); // Hapus token
        break;
      }
    }
    return { success: true };
  } catch (e) {
    return { success: false };
  } finally {
    lock.releaseLock();
  }
}

// --- DASHBOARD STATS ---
function getDashboardStats() {
  const karyawan = parseData('Karyawan', (r, m) => ({ 
    id: String(r[m['id']]), nama: r[m['nama']], jabatan: r[m['jabatan']], status: r[m['status']] 
  }));
  const iuran = parseData('Iuran', (r, m) => ({ 
    id: Number(r[m['id']]) || 0, id_karyawan: String(r[m['id_karyawan']]), nama_karyawan: r[m['nama_karyawan']],
    tanggal: safeDateFormat(r[m['tanggal']]), nominal: parseFloat(r[m['nominal']]) || 0 
  }));
  const pengeluaran = parseData('Pengeluaran', (r, m) => ({
    id: Number(r[m['id']]) || 0, tanggal: safeDateFormat(r[m['tanggal']]),
    keterangan: r[m['keterangan']], nominal: parseFloat(r[m['nominal']]) || 0
  }));
  const settings = parseData('Settings', (r, m) => ({ key: r[m['key']], value: r[m['value']] }));

  // Hitung Belum Giliran
  let belumGiliran = 0;
  const mapKar = {};
  karyawan.forEach(k => {
    mapKar[k.id] = k.jabatan;
    if (k.status === 'Belum') belumGiliran++;
  });

  // DETEKSI BULAN INI
  const d = new Date();
  const curMonth = Utilities.formatDate(d, Session.getScriptTimeZone(), 'MM');
  const curYear = Utilities.formatDate(d, Session.getScriptTimeZone(), 'yyyy');
  const namaBulanIndo = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];
  const namaBulanAktif = namaBulanIndo[d.getMonth()]; 

  let totalPNS = 0, totalP3K = 0, totalP3KPWD = 0, totalP3KPW = 0, totalLainnya = 0;
  let totalIuranBulanIni = 0; // <-- Diubah agar otomatis 0 setiap ganti bulan
  const iuranBulanIni = {}; 

  iuran.forEach(i => {
    if (i.tanggal && i.tanggal.length >= 7) {
      // Hanya jumlahkan uang masuk di bulan dan tahun yang sama dengan hari ini
      if (i.tanggal.substring(0,4) === curYear && i.tanggal.substring(5,7) === curMonth) {
         iuranBulanIni[i.id_karyawan] = (iuranBulanIni[i.id_karyawan] || 0) + i.nominal;
         totalIuranBulanIni += i.nominal;
         
         let jab = mapKar[i.id_karyawan];
         if (jab === 'PNS') totalPNS += i.nominal;
         else if (jab === 'P3K') totalP3K += i.nominal;
         else if (jab === 'P3KPWD') totalP3KPWD += i.nominal;
         else if (jab === 'P3KPW') totalP3KPW += i.nominal;
         else totalLainnya += i.nominal;
      }
    }
  });

  // LOGIKA PENGELUARAN DINAMIS (Cari bulan terakhir yang ada transaksinya)
  let pengeluaranBulanIni = 0; 
  let latestExpMonthStr = "";
  let latestExpYearStr = "";
  let totalPengeluaranLatest = 0;
  let namaBulanPengeluaran = "Belum Ada";

  if (pengeluaran.length > 0) {
    let latestDate = "0000-00-00";
    pengeluaran.forEach(p => {
      if (p.tanggal && p.tanggal > latestDate) latestDate = p.tanggal;
    });

    if (latestDate !== "0000-00-00") {
      latestExpYearStr = latestDate.substring(0, 4);
      latestExpMonthStr = latestDate.substring(5, 7);
      let monthIndex = parseInt(latestExpMonthStr, 10) - 1;
      if (monthIndex >= 0 && monthIndex < 12) {
        namaBulanPengeluaran = namaBulanIndo[monthIndex] + (latestExpYearStr !== curYear ? " " + latestExpYearStr : "");
      }
    }
    
    pengeluaran.forEach(p => {
      if (p.tanggal && p.tanggal.length >= 7) {
        let pYear = p.tanggal.substring(0,4);
        let pMonth = p.tanggal.substring(5,7);
        
        // Total untuk ditampilkan di Kartu Dashboard (Mengikuti transaksi terakhir)
        if (pYear === latestExpYearStr && pMonth === latestExpMonthStr) {
          totalPengeluaranLatest += p.nominal;
        }
        
        // Total murni bulan ini (Untuk memotong Saldo Kas menjadi 0 saat berganti bulan)
        if (pYear === curYear && pMonth === curMonth) {
          pengeluaranBulanIni += p.nominal;
        }
      }
    });
  }

  let aktivitas = [];
  iuran.forEach(i => aktivitas.push({ id: i.id, tgl: i.tanggal, keterangan: 'Pembayaran Iuran - ' + i.nama_karyawan, nominal: i.nominal, status: 'Masuk' }));
  pengeluaran.forEach(p => aktivitas.push({ id: p.id, tgl: p.tanggal, keterangan: 'Biaya ' + p.keterangan, nominal: p.nominal, status: 'Keluar' }));
  aktivitas.sort((a, b) => {
    let diff = new Date(b.tgl) - new Date(a.tgl);
    return diff === 0 ? b.id - a.id : diff;
  });

  let infoHariIni = "Selamat datang di sistem e-Anjangsana!";
  let waTemplateStr = "";
  settings.forEach(s => {
    if (s.key === 'info_dashboard') infoHariIni = s.value;
    if (s.key === 'wa_template') waTemplateStr = s.value;
  });

  const belumBayarList = [];
  karyawan.forEach(k => {
    if (!iuranBulanIni[k.id] || iuranBulanIni[k.id] <= 0) {
       belumBayarList.push({ nama: k.nama });
    }
  });
  belumBayarList.sort((a,b) => a.nama.localeCompare(b.nama));

  return {
    success: true,
    data: {
      belumBayarList: belumBayarList,
      totalPNS: totalPNS,
      totalP3K: totalP3K,
      totalP3KPWD: totalP3KPWD,
      totalP3KPW: totalP3KPW,
      totalLainnya: totalLainnya,
      totalIuran: totalIuranBulanIni,
      totalPengeluaran: totalPengeluaranLatest,
      saldo: totalIuranBulanIni - pengeluaranBulanIni, // <-- Saldo hanya mutasi bulan aktif
      belumGiliran: belumGiliran,
      aktivitas: aktivitas,
      info: infoHariIni,
      wa_template: waTemplateStr,
      bulanAktif: namaBulanAktif,
      bulanPengeluaran: namaBulanPengeluaran // <-- Info nama bulan untuk kartu Pengeluaran
    }
  };
}

// --- GET DATA FUNCTIONS ---
function getUsers() {
  const data = parseData('Users', (row, map) => ({
    username: row[map['username']],
    // PASSWORD TIDAK DITAMPILKAN KE FRONTEND DEMI KEAMANAN
    fullname: row[map['fullname']],
    role: row[map['role']],
    photo: row[map['photo']] || ''
  }));
  return { success: true, data: data };
}

function getKaryawan() {
  const data = parseData('Karyawan', (row, map) => ({
    id: row[map['id']], nama: row[map['nama']], jabatan: row[map['jabatan']],
    nominal_iuran: row[map['nominal_iuran']], status: row[map['status']]
  }));
  return { success: true, data: data.sort((a, b) => a.nama.localeCompare(b.nama)) };
}

function getIuran() {
  const data = parseData('Iuran', (row, map) => {
    // Mencegah error jika Google Sheets otomatis mengubah teks "April 2026" jadi Tanggal (Date)
    let valPeriode = row[map['periode']];
    if (valPeriode instanceof Date) {
      let bulan = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];
      valPeriode = bulan[valPeriode.getMonth()] + ' ' + valPeriode.getFullYear();
    } else {
      valPeriode = String(valPeriode || '');
    }

    return {
      id: row[map['id']], tanggal: safeDateFormat(row[map['tanggal']]),
      id_karyawan: row[map['id_karyawan']], nama_karyawan: String(row[map['nama_karyawan']]),
      periode: valPeriode, nominal: row[map['nominal']],
      metode_pembayaran: String(row[map['metode_pembayaran']]), uang_diterima: row[map['uang_diterima']], kembalian: row[map['kembalian']]
    };
  });
  return { success: true, data: data.reverse() };
}

function getPengeluaran() {
  const data = parseData('Pengeluaran', (row, map) => ({
    id: row[map['id']], tanggal: safeDateFormat(row[map['tanggal']]),
    keterangan: row[map['keterangan']], nominal: row[map['nominal']], kategori: row[map['kategori']]
  }));
  return { success: true, data: data.reverse() };
}

function getUndian() {
  const data = parseData('Undian', (row, map) => {
    // Mencegah error jika kolom periode diubah otomatis jadi Tanggal oleh Google Sheets
    let valPeriode = row[map['periode']];
    if (valPeriode instanceof Date) {
      let bulan = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];
      valPeriode = bulan[valPeriode.getMonth()] + ' ' + valPeriode.getFullYear();
    } else {
      valPeriode = String(valPeriode || '');
    }

    return {
      id: row[map['id']], tanggal: safeDateFormat(row[map['tanggal']]),
      id_karyawan: row[map['id_karyawan']], nama_pemenang: String(row[map['nama_pemenang']]), periode: valPeriode
    };
  });
  return { success: true, data: data.reverse() };
}

// --- SAVE FUNCTIONS ---
function saveDataGeneral(sheetName, payload, mapFn) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(sheetName);
    if (!sheet) throw new Error("Sheet " + sheetName + " tidak ditemukan.");
    
    const map = getColumnMap(sheet);
    const dataId = payload.dataId;
    const isEdit = payload.isEdit === 'true';
    
    const rowData = [];
    for(let i=0; i<Object.keys(map).length; i++) rowData.push('');
    
    mapFn(payload, rowData, map);
    
    if (isEdit) {
      const data = sheet.getDataRange().getValues();
      let rowIndex = -1;
      for (let i = 1; i < data.length; i++) {
        if (String(data[i][map['id']]) === String(dataId)) { rowIndex = i + 1; break; }
      }
      if (rowIndex !== -1) {
        sheet.getRange(rowIndex, 1, 1, rowData.length).setValues([rowData]);
      } else {
        throw new Error("Data tidak ditemukan.");
      }
    } else {
      sheet.appendRow(rowData);
    }
    return { success: true };
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function saveUser(payload) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName('Users');
    if (!sheet) throw new Error("Sheet Users tidak ditemukan.");

    const map = getColumnMap(sheet);
    const data = sheet.getDataRange().getValues();
    const isEdit = payload.isEdit === 'true';
    
    // Keamanan: Jika password diisi, Hash. Jika kosong, biarkan (untuk Edit)
    const rawPass = payload.password.trim();
    const finalPassHash = rawPass ? hashPassword(rawPass) : '';

    if (isEdit) {
      let rowIndex = -1;
      for (let i = 1; i < data.length; i++) {
        if (String(data[i][map['username']]) === String(payload.dataId)) { rowIndex = i + 1; break; }
      }
      if (rowIndex !== -1) {
        if (payload.username !== payload.dataId) {
           for (let i = 1; i < data.length; i++) {
             if (String(data[i][map['username']]) === String(payload.username)) throw new Error("Username sudah dipakai.");
           }
        }
        sheet.getRange(rowIndex, map['username'] + 1).setValue(payload.username);
        // Hanya ganti password jika diisi password baru
        if (finalPassHash) {
          sheet.getRange(rowIndex, map['password'] + 1).setValue(finalPassHash);
        }
        sheet.getRange(rowIndex, map['fullname'] + 1).setValue(payload.fullname);
        sheet.getRange(rowIndex, map['role'] + 1).setValue(payload.role);
        sheet.getRange(rowIndex, map['photo'] + 1).setValue(payload.photo || '');
      } else {
        throw new Error("User tidak ditemukan.");
      }
    } else {
      for (let i = 1; i < data.length; i++) {
         if (String(data[i][map['username']]) === String(payload.username)) throw new Error("Username sudah dipakai.");
      }
      if (!finalPassHash) throw new Error("Password wajib diisi untuk user baru.");
      
      const rowData = [];
      for(let i=0; i<Object.keys(map).length; i++) rowData.push('');
      rowData[map['username']] = payload.username;
      rowData[map['password']] = finalPassHash;
      rowData[map['fullname']] = payload.fullname;
      rowData[map['role']] = payload.role;
      rowData[map['photo']] = payload.photo || '';
      rowData[map['token']] = ''; // default kosong saat create
      sheet.appendRow(rowData);
    }
    return { success: true };
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function saveKaryawan(payload) {
  return saveDataGeneral('Karyawan', payload, (p, r, m) => {
    r[m['id']] = p.isEdit === 'true' ? p.dataId : new Date().getTime();
    r[m['nama']] = p.nama; r[m['jabatan']] = p.jabatan; 
    r[m['nominal_iuran']] = p.nominal_iuran; r[m['status']] = p.status;
  });
}

function saveIuran(payload) {
  return saveDataGeneral('Iuran', payload, (p, r, m) => {
    r[m['id']] = p.isEdit === 'true' ? p.dataId : new Date().getTime();
    r[m['tanggal']] = p.tanggal; r[m['id_karyawan']] = p.id_karyawan;
    r[m['nama_karyawan']] = p.nama_karyawan; r[m['periode']] = p.periode; r[m['nominal']] = p.nominal;
    r[m['metode_pembayaran']] = p.metode_pembayaran; r[m['uang_diterima']] = p.uang_diterima; r[m['kembalian']] = p.kembalian;
  });
}

function savePengeluaran(payload) {
  return saveDataGeneral('Pengeluaran', payload, (p, r, m) => {
    r[m['id']] = p.isEdit === 'true' ? p.dataId : new Date().getTime();
    r[m['tanggal']] = p.tanggal; r[m['keterangan']] = p.keterangan;
    r[m['nominal']] = p.nominal; r[m['kategori']] = p.kategori;
  });
}

function saveUndian(payload) {
  let resUndian = saveDataGeneral('Undian', payload, (p, r, m) => {
    r[m['id']] = p.isEdit === 'true' ? p.dataId : new Date().getTime();
    r[m['tanggal']] = p.tanggal; r[m['id_karyawan']] = p.id_karyawan;
    r[m['nama_pemenang']] = p.nama_pemenang; r[m['periode']] = p.periode;
  });

  if (!resUndian.success) return resUndian;

  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheetKar = ss.getSheetByName('Karyawan');
    if (sheetKar) {
       const data = sheetKar.getDataRange().getValues();
       const map = getColumnMap(sheetKar);
       const targetId = String(payload.id_karyawan);
       for(let i = 1; i < data.length; i++) {
         if(String(data[i][map['id']]) === targetId) {
            sheetKar.getRange(i + 1, map['status'] + 1).setValue('Sudah');
            break;
         }
       }
    }
    return { success: true };
  } catch(e) {
    return { success: true }; 
  } finally {
    lock.releaseLock();
  }
}

function saveSettingInfo(infoText) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    let sheet = ss.getSheetByName('Settings');
    if (!sheet) return { success: false, message: 'Sheet Settings tidak ditemukan.' };
    
    const data = sheet.getDataRange().getValues();
    let found = false;
    for (let i = 1; i < data.length; i++) {
      if (data[i][0] === 'info_dashboard') {
        sheet.getRange(i + 1, 2).setValue(infoText);
        found = true;
        break;
      }
    }
    if (!found) sheet.appendRow(['info_dashboard', infoText]);
    return { success: true };
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function saveSettingWA(templateText) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    let sheet = ss.getSheetByName('Settings');
    if (!sheet) return { success: false, message: 'Sheet Settings tidak ditemukan.' };
    
    const data = sheet.getDataRange().getValues();
    let found = false;
    for (let i = 1; i < data.length; i++) {
      if (data[i][0] === 'wa_template') {
        sheet.getRange(i + 1, 2).setValue(templateText);
        found = true;
        break;
      }
    }
    if (!found) sheet.appendRow(['wa_template', templateText]);
    return { success: true };
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function resetStatusKaryawan() {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName('Karyawan');
    if (!sheet) throw new Error("Sheet Karyawan tidak ditemukan.");

    const map = getColumnMap(sheet);
    if (map['status'] === undefined) throw new Error("Kolom status tidak ditemukan.");

    const data = sheet.getDataRange().getValues();
    const statusColIdx = map['status'] + 1;

    for (let i = 1; i < data.length; i++) {
      sheet.getRange(i + 1, statusColIdx).setValue('Belum');
    }
    return { success: true };
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

// --- DELETE FUNCTIONS ---
function deleteDataGeneral(sheetName, id) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(sheetName);
    if (!sheet) throw new Error("Sheet tidak ditemukan.");
    
    const data = sheet.getDataRange().getValues();
    const map = getColumnMap(sheet);
    let rowIndex = -1;
    for (let i = 1; i < data.length; i++) {
      if (String(data[i][map['id']]) === String(id)) { rowIndex = i + 1; break; }
    }
    if (rowIndex !== -1) { sheet.deleteRow(rowIndex); } 
    else { throw new Error("Data tidak ditemukan."); }
    
    return { success: true };
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function deleteUser(username) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName('Users');
    if (!sheet) throw new Error("Sheet Users tidak ditemukan.");

    const data = sheet.getDataRange().getValues();
    const map = getColumnMap(sheet);
    let rowIndex = -1;
    for (let i = 1; i < data.length; i++) {
      if (String(data[i][map['username']]) === String(username)) { rowIndex = i + 1; break; }
    }
    if (rowIndex !== -1) {
       if (username === 'admin') throw new Error("Superadmin utama tidak boleh dihapus!");
       sheet.deleteRow(rowIndex);
    }
    else { throw new Error("User tidak ditemukan."); }

    return { success: true };
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}

function deleteKaryawan(id) { return deleteDataGeneral('Karyawan', id); }
function deleteIuran(id) { return deleteDataGeneral('Iuran', id); }
function deletePengeluaran(id) { return deleteDataGeneral('Pengeluaran', id); }
function deleteUndian(id) {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(10000);
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheetUndian = ss.getSheetByName('Undian');
    if (!sheetUndian) throw new Error("Sheet Undian tidak ditemukan.");

    const dataU = sheetUndian.getDataRange().getValues();
    const mapU = getColumnMap(sheetUndian);
    let rowIndex = -1;
    let idKaryawan = '';

    // Cari baris undian yang akan dihapus
    for (let i = 1; i < dataU.length; i++) {
      if (String(dataU[i][mapU['id']]) === String(id)) {
        rowIndex = i + 1;
        idKaryawan = String(dataU[i][mapU['id_karyawan']]);
        break;
      }
    }

    if (rowIndex !== -1) {
      // 1. Hapus dari daftar Undian
      sheetUndian.deleteRow(rowIndex);
      
      // 2. Otomatis kembalikan statusnya di tabel Karyawan
      if (idKaryawan) {
         const sheetKar = ss.getSheetByName('Karyawan');
         if (sheetKar) {
           const dataK = sheetKar.getDataRange().getValues();
           const mapK = getColumnMap(sheetKar);
           for(let i = 1; i < dataK.length; i++) {
             if(String(dataK[i][mapK['id']]) === idKaryawan) {
                sheetKar.getRange(i + 1, mapK['status'] + 1).setValue('Belum');
                break;
             }
           }
         }
      }
    } else {
      throw new Error("Data tidak ditemukan.");
    }

    return { success: true };
  } catch (e) {
    return { success: false, message: e.toString() };
  } finally {
    lock.releaseLock();
  }
}
// --- FUNGSI PANCING IZIN OTORISASI ---
function pancingIzin() {
  try {
    // Memanggil layanan Spreadsheet dan LockService untuk memancing izin
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const lock = LockService.getScriptLock();
    
    Logger.log("Pancingan berhasil!");
    Logger.log("Terhubung dengan database: " + ss.getName());
    Logger.log("Semua izin akses script telah di-reset dan diberikan ulang.");
  } catch (e) {
    Logger.log("Error: " + e.toString());
  }
}

// --- FUNGSI DOWNLOAD APK ANDROID ---
function prepareExport(csvContent) {
  var id = Utilities.getUuid();
  CacheService.getScriptCache().put('export_' + id, csvContent, 600); // Simpan sementara 10 menit
  return ScriptApp.getService().getUrl() + '?export_id=' + id;
}

function getWaTemplate() {
  var lock = LockService.getScriptLock();
  try {
    lock.waitLock(5000);
    const sheet = SpreadsheetApp.getActiveSpreadsheet().getSheetByName('Settings');
    if (!sheet) return "";
    
    const data = sheet.getDataRange().getValues();
    for (let i = 1; i < data.length; i++) {
      if (data[i][0] === 'wa_template') {
        return data[i][1]; // Mengirim teks asli langsung dari sel
      }
    }
    return "";
  } catch (e) {
    return "";
  } finally {
    lock.releaseLock();
  }
}
